services:
  ddd_app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "18080:8080" # 必要に応じてポートを調整してください
    depends_on:
      ddd_rdb:
        condition: service_healthy

  ddd_rdb:
    build:
      context: ./rdb
      dockerfile: Dockerfile
    ports:
      - "13306:3306" # 必要に応じてポートを調整してください
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  db_data:
