version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - plant-network

  backend:
    image: golang:1.21-alpine
    working_dir: /app
    volumes:
      - ../../repos/agent-test:/app
    ports:
      - "8080:8080"
    command: go run main.go
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=plantdb
    depends_on:
      - db
    networks:
      - plant-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=plantdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - plant-network

volumes:
  mysql_data:

networks:
  plant-network:
    driver: bridge
