# .golangci.yml
run:
  # Issue があっても 0 を返す
  issues-exit-code: 0      # デフォルト 1 → 0 に変更  :contentReference[oaicite:0]{index=0}

issues:
  # マッチした Issue を完全に抑制
  exclude:
    - ".*"                 # すべてのメッセージに一致  :contentReference[oaicite:1]{index=1}
