pkgname = "db"
output = "db"
wipe = true                 # 前回生成したコードを毎回削除
add-global-variants = false # グローバル構造体を使用する関数を生成するか
no-tests = true             # テストコードを作成するか

[mysql]
  dbname     = "test"
  host       = "127.0.0.1"
  port       = 3306
  user       = "root"
  pass       = "root"
  sslmode    = "false"
  whitelist = [
    "articles",
    "users"
  ]