services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.12.0
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      # 不要っぽい
      # SWAGGER_JSON: /usr/share/nginx/html/openapi.yaml
      API_URL: openapi.yaml
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      retries: 3