services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - app-network
  app:
    build: .
    depends_on:
      - redis
    command: ["/go-redis-app"]
    ports:
      - 3000:3000
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge

